from . import account_tax_template
from . import account_journal
from . import account_move_line
from . import account_move
from . import account_payment
from . import account_payment_term
from . import api_facturae
from . import code_type_product
from . import fe_enums
from . import identification_type
from . import product_template
from . import product_category
from . import reference_code
from . import reference_document
from . import res_company
from . import res_partner_cabys_line
from . import res_partner
from . import res_config_settings
from . import resolution
from . import sale_condition
from . import uom
from . import aut_ex
from . import account_tax
from . import economic_activity
from . import qr_generator
from . import invoice_qr_fields
